spring:
 profiles:
   active:
    - dev
---
spring:
 profiles: dev  #开发环境
 application:
  name:microservicecloud-config-intact-dev  
---
sping:
 profiles: test  #测试环境
 application:
  name: microservicecloud-config-intact-test
#请保存为UTF-8格式
    